#!/bin/sh

set -e

lb config noauto \
  --apt-recommends true \
  --apt-indices false \
  --architectures amd64 \
  --archive-areas 'main contrib non-free' \
  --backports false \
  --security true \
  --updates true \
  --source false \
  --binary-filesystem ext4 \
  --binary-images iso-hybrid \
  --checksums sha256 \
  --debconf-frontend noninteractive \
  --debian-installer none \
  --debian-installer-gui false \
  --debootstrap-options "--variant=minbase --include=apt-transport-https,ca-certificates,openssl" \
  --distribution bullseye \
  --mode debian \
  --system live \
  --bootappend-live "boot=live components quiet splash" \
  --linux-package "linux-image" \
  --iso-application "Debian Live HPE SSA" \
  --memtest none \
  --clean \
  --debug \
  --verbose \
  "${@}"
