#!/bin/sh

set -e

lb config noauto \
	--mode "debian" \
	--system "live" \
	--architectures "amd64" \
	--distribution "bullseye" \
	--bootappend-live "boot=live components quiet noswap" \
	--archive-areas "main contrib non-free" \
	--security "true" \
	--updates "true" \
	--backports "false" \
	--binary-images "iso-hybrid" \
	--apt-indices "true" \
	--apt-recommends "false" \
	--apt-secure "true" \
	--apt-source-archives "true" \
	--linux-package "linux-image" \
	--bootloader "syslinux" \
	--debian-installer "none" \
	--debian-installer-gui "false" \
	--iso-application "Debian Live HPE SSA" \
	--memtest "none" \
	--clean \
	--debug \
	--verbose \
	--source "false" \
	"${@}"
